version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      # אם יש צורך להגדיר משתני סביבה עבור backend
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: '1234'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15  # השתמש בגרסה עדכנית
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        retries: 5
        timeout: 3s


networks:
  app-network:
    driver: bridge

volumes:
  pgdata:

